# Generated by Django 2.2.1 on 2019-05-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInformations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_num', models.CharField(max_length=7)),
                ('passengers_num', models.IntegerField()),
                ('production_year', models.IntegerField()),
                ('car_category', models.IntegerField(choices=[(0, 'economy'), (1, 'business'), (2, 'first class')], default=0)),
                ('more_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.TextField()),
                ('model', models.TextField()),
                ('car_type', models.IntegerField(choices=[(0, 'sedan'), (1, 'limousine'), (5, 'mini-bus'), (3, 'SUV'), (2, 'van'), (4, 'stretch limousine')], default=0)),
                ('car_informations', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talixo.CarInformations')),
            ],
        ),
    ]
