# Generated by Django 2.2.1 on 2019-05-14 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talixo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinformations',
            name='car_category',
            field=models.IntegerField(choices=[(2, 'first class'), (1, 'business'), (0, 'economy')], default=0),
        ),
        migrations.AlterField(
            model_name='carlist',
            name='car_informations',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='talixo.CarInformations'),
        ),
        migrations.AlterField(
            model_name='carlist',
            name='car_type',
            field=models.IntegerField(choices=[(5, 'mini-bus'), (2, 'van'), (0, 'sedan'), (3, 'SUV'), (4, 'stretch limousine'), (1, 'limousine')], default=0),
        ),
    ]
