# Generated by Django 2.2.1 on 2019-05-14 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talixo', '0002_auto_20190514_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinformations',
            name='car_category',
            field=models.IntegerField(choices=[(1, 'business'), (0, 'economy'), (2, 'first class')], default=0),
        ),
        migrations.AlterField(
            model_name='carlist',
            name='car_informations',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='talixo.CarInformations'),
        ),
        migrations.AlterField(
            model_name='carlist',
            name='car_type',
            field=models.IntegerField(choices=[(5, 'mini-bus'), (2, 'van'), (0, 'sedan'), (4, 'stretch limousine'), (1, 'limousine'), (3, 'SUV')], default=0),
        ),
    ]
