# Generated by Django 2.2.1 on 2019-05-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talixo', '0003_auto_20190514_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='car_informations',
            new_name='details',
        ),
        migrations.AlterField(
            model_name='carinformations',
            name='car_category',
            field=models.IntegerField(choices=[(2, 'first class'), (0, 'economy'), (1, 'business')], default=0),
        ),
        migrations.AlterField(
            model_name='carlist',
            name='car_type',
            field=models.IntegerField(choices=[(1, 'limousine'), (4, 'stretch limousine'), (0, 'sedan'), (5, 'mini-bus'), (2, 'van'), (3, 'SUV')], default=0),
        ),
    ]
